In [1]:
#download word2vec model
#!wget http://www.arts.chula.ac.th/ling/wp-content/uploads/TNCc5model.bin

In [2]:
import tltk
#download word2vec from TLTK
tltk.corpus.w2v_load()

paramiko missing, opening SSH/SCP/SFTP paths will be disabled.  `pip install paramiko` to suppress


1

![title](http://ruder.io/content/images/2018/07/word2vec_relations.png)

In [3]:
print(tltk.corpus.analogy('พระราชา','พระราชินี','ผู้หญิง'))

[('ผู้ชาย', 0.7522006034851074)]


In [4]:
print(tltk.corpus.analogy('ผู้ชาย','ผู้หญิง','พยาบาล'))

[('แพทย์', 0.5493806600570679)]


In [5]:
print(tltk.corpus.analogy('ผู้หญิง','ผู้ชาย','นักสืบ'))

[('ไกด์', 0.6317105293273926)]


In [6]:
print(tltk.corpus.analogy('ผู้ชาย','ผู้หญิง','หมอตำแย'))

[('จิ๊กโก๋', 0.7184369564056396)]


In [7]:
print(tltk.corpus.analogy('ผู้ชาย','ผู้หญิง','ดีไซเนอร์'))

[('ศิลปิน', 0.7169309854507446)]


In [8]:
print(tltk.corpus.analogy('ผู้ชาย','ผู้หญิง','แม่บ้าน'))

[('กุลี', 0.6624711751937866)]


![title](https://i1.rgstatic.net/publication/305615978_Man_is_to_Computer_Programmer_as_Woman_is_to_Homemaker_Debiasing_Word_Embeddings/links/57a20cd508aeef8f311e0871/largepreview.png)

# to do: prep data
1. Download dataset -- done
2. normalize each word to unit length


In [184]:
from gensim.test.utils import common_texts, get_tmpfile
from gensim.test.utils import datapath
from gensim.models import KeyedVectors
from gensim.models import Word2Vec
model = Word2Vec.load("TNCc5model.bin")
path = get_tmpfile("wordvectors.kv")
model.wv.save(path)
norm_wv = KeyedVectors.load(path, mmap='r')
new_wv = KeyedVectors.load(path, mmap='r')#เรา จะเก็บdebiasในตัวนี้


In [185]:
model.wv["ผู้ชาย"]

array([ 3.79300070e+00, -1.66482031e+00, -7.60671973e-01,  1.16929546e-01,
       -5.51230833e-03, -2.43274286e-01,  4.79112029e-01, -6.80777848e-01,
        7.93788552e-01, -7.47233570e-01,  8.70086133e-01,  1.88816249e+00,
        2.47819960e-01,  1.13803744e+00, -2.59251976e+00,  1.04245687e+00,
       -8.64011168e-01,  1.10866404e+00, -2.46860647e+00,  7.96355188e-01,
       -1.52359617e+00, -4.65069473e-01,  3.96931060e-02,  1.34157276e+00,
       -2.04626369e+00,  6.78536832e-01, -1.42161667e+00,  3.62649888e-01,
        2.78280258e+00, -2.57205099e-01, -8.99130523e-01,  7.67076969e-01,
        3.57866669e+00,  1.07708228e+00, -4.02716137e-02, -5.34867108e-01,
        3.47196907e-01, -8.04353356e-01,  3.35953891e-01, -7.50370860e-01,
        1.27186930e+00, -4.52440351e-01,  1.22051346e+00, -7.16886878e-01,
        9.20982182e-01,  2.08331084e+00,  3.48603320e+00,  1.06670475e+00,
       -1.20950782e+00,  5.53042769e-01,  2.47182474e-02,  1.50332272e+00,
       -1.53137565e+00, -

In [186]:
norm_wv.init_sims(replace=True)
norm_wv['ผู้ชาย']

array([ 2.80013025e-01, -1.22903049e-01, -5.61555550e-02,  8.63216165e-03,
       -4.06938518e-04, -1.79593880e-02,  3.53697799e-02, -5.02574816e-02,
        5.86003400e-02, -5.51634841e-02,  6.42329007e-02,  1.39390975e-01,
        1.82949658e-02,  8.40140358e-02, -1.91389173e-01,  7.69579336e-02,
       -6.37844279e-02,  8.18455890e-02, -1.82241455e-01,  5.87898195e-02,
       -1.12477377e-01, -3.43331099e-02,  2.93028844e-03,  9.90397483e-02,
       -1.51062578e-01,  5.00920415e-02, -1.04948878e-01,  2.67721247e-02,
        2.05436543e-01, -1.89878102e-02, -6.63770661e-02,  5.66283949e-02,
        2.64190108e-01,  7.95141086e-02, -2.97299610e-03, -3.94858234e-02,
        2.56313309e-02, -5.93802705e-02,  2.48013306e-02, -5.53950891e-02,
        9.38939899e-02, -3.34007815e-02,  9.01027173e-02, -5.29231802e-02,
        6.79902360e-02,  1.53797537e-01,  2.57351577e-01,  7.87480026e-02,
       -8.92902389e-02,  4.08276170e-02,  1.82479038e-03,  1.10980719e-01,
       -1.13051683e-01, -

In [187]:
new_wv.init_sims(replace=True)
new_wv['ผู้ชาย']

array([ 2.80013025e-01, -1.22903049e-01, -5.61555550e-02,  8.63216165e-03,
       -4.06938518e-04, -1.79593880e-02,  3.53697799e-02, -5.02574816e-02,
        5.86003400e-02, -5.51634841e-02,  6.42329007e-02,  1.39390975e-01,
        1.82949658e-02,  8.40140358e-02, -1.91389173e-01,  7.69579336e-02,
       -6.37844279e-02,  8.18455890e-02, -1.82241455e-01,  5.87898195e-02,
       -1.12477377e-01, -3.43331099e-02,  2.93028844e-03,  9.90397483e-02,
       -1.51062578e-01,  5.00920415e-02, -1.04948878e-01,  2.67721247e-02,
        2.05436543e-01, -1.89878102e-02, -6.63770661e-02,  5.66283949e-02,
        2.64190108e-01,  7.95141086e-02, -2.97299610e-03, -3.94858234e-02,
        2.56313309e-02, -5.93802705e-02,  2.48013306e-02, -5.53950891e-02,
        9.38939899e-02, -3.34007815e-02,  9.01027173e-02, -5.29231802e-02,
        6.79902360e-02,  1.53797537e-01,  2.57351577e-01,  7.87480026e-02,
       -8.92902389e-02,  4.08276170e-02,  1.82479038e-03,  1.10980719e-01,
       -1.13051683e-01, -

# Exploratory analysis: Occupational stereotypes.
1) evaluate whether the embedding has stereotypes on occupation words and 2) evaluate whether the embedding produces analogies that are judged to reflect stereotypes by humans

1. lists the occupations that are closest to she and to he in the embeddings.
2. ask the crowdworkers to evaluate whether an occupation is considered female-stereotypic, male-stereotypic, or neutral

![title](https://pbs.twimg.com/media/DVdqoEHVoAAlJ4g.jpg)

![title](https://cdn-images-1.medium.com/max/858/1*keqyBCQ5FL6A7DZLrXamvQ.png)

![title](http://mathonline.wdfiles.com/local--files/vector-projections/Screen%20Shot%202014-12-14%20at%2012.42.18%20PM.png)


In [12]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import random

gender_dir = norm_wv['หญิง'] - norm_wv['ชาย']
gender_projection = lambda x : np.dot(x, gender_dir) / np.linalg.norm(gender_dir)
#ต้องยืดมากแค่ไหนถึงจะproject ลงบน gender_dir พอดี

In [13]:
occupation_list=['พยาบาล','แพทย์','ไกด์','นักสืบ','หมอตำแย','ดีไซเนอร์','ศิลปิน','ตำรวจ','ทหาร','อัยการ'
                 ,'แอร์โฮสเตส','นักเคมี', 'เภสัชกร','ช่าง','ช่างภาพ','นักการเมือง','นักการทูต','ทนาย'
                 ,'กะลาสี','นักวิทยาศาสตร์','นักแสดง','บรรณาธิการ','ผู้กำกับ','พี่เลี้ยง','มัคคุเทศก์','คนงาน'
                 ,'บรรณาธิการ','บรรณารักษ์','นักเขียน','จิตแพทย์','เพชฌฆาต','สัตวแพทย์','คอลัมนิสต์','มือปืน'
                ,'นักข่าว','นักธุรกิจ','นักมวย','นักบิน','คนใช้','คนสวน','ชาวไร่','ชาวนา','นักกีฬา','นักวิ่ง'
                ,'จิตรกร','นักร้อง','สถาปนิก','ศาสตราจารย์','กรรมกร','อาจารย์','ครู','วิศวกร','ศัลยแพทย์']

In [14]:
len(occupation_list)

53

In [15]:
rank_job = dict.fromkeys(occupation_list)
for n in occupation_list:
    rank_job[n]= gender_projection(norm_wv[n])
rank_job = sorted(rank_job.items(), key=lambda kv: kv[1])
rank_job.reverse()

In [16]:
rank_job

[('แอร์โฮสเตส', 0.34675175),
 ('พยาบาล', 0.1656979),
 ('อาจารย์', 0.13835084),
 ('คอลัมนิสต์', 0.13245864),
 ('นักข่าว', 0.11810425),
 ('ครู', 0.11230043),
 ('ผู้กำกับ', 0.07558014),
 ('นักแสดง', 0.069970086),
 ('วิศวกร', 0.06743736),
 ('ศาสตราจารย์', 0.05827758),
 ('ดีไซเนอร์', 0.05434611),
 ('มัคคุเทศก์', 0.05304229),
 ('นักร้อง', 0.04557085),
 ('ไกด์', 0.043560926),
 ('ช่างภาพ', 0.037830215),
 ('นักการทูต', 0.034043066),
 ('ศัลยแพทย์', 0.03171372),
 ('บรรณาธิการ', 0.030348293),
 ('ศิลปิน', 0.023446834),
 ('บรรณารักษ์', 0.022214444),
 ('ช่าง', 0.010418928),
 ('นักสืบ', 0.0086339535),
 ('แพทย์', 0.0084077725),
 ('นักกีฬา', 0.0071754362),
 ('พี่เลี้ยง', 0.0062602796),
 ('นักวิทยาศาสตร์', 0.0034829034),
 ('นักเคมี', -0.0014757313),
 ('นักการเมือง', -0.0027038727),
 ('นักธุรกิจ', -0.005431537),
 ('อัยการ', -0.0071990113),
 ('นักเขียน', -0.011493621),
 ('คนสวน', -0.019015025),
 ('หมอตำแย', -0.049030222),
 ('ชาวไร่', -0.050195646),
 ('มือปืน', -0.059419192),
 ('คนใช้', -0.061974686),
 ('สถ

# Exploratory analysis: Analogies exhibiting stereotypes. 
1) evaluate whether the embedding has stereotypes on occupation words and 2) evaluate whether the embedding produces analogies that are judged to reflect stereotypes by humans

1. systematically generate pairs of words that the embedding believes it analogous to he, she (or any other pair of seed words). 
2. qualitative analysis



In [17]:
#of word
len(norm_wv.vocab)

31078

In [18]:
pair_dict = dict()
delta = 1.0


In [19]:
%%time
for i in range(100000000):
    x_word=random.choice(norm_wv.index2word)
    y_word=random.choice(norm_wv.index2word)
    if np.linalg.norm(norm_wv[x_word]-norm_wv[y_word]) <= delta:
        pair_dict[x_word+"_"+y_word]=cosine_similarity([gender_dir],[norm_wv[x_word]-norm_wv[y_word]])[0][0]
        

CPU times: user 47min 30s, sys: 4.74 s, total: 47min 35s
Wall time: 47min 39s


In [20]:
pair_dict = sorted(pair_dict.items(), key=lambda kv: kv[1])
pair_dict.reverse()

In [21]:
pair_dict

[('หญิง_ผู้หญิง', 0.53789485),
 ('หมวย_สาว', 0.5105653),
 ('พี่_ลุง', 0.49465287),
 ('หลาน_เหลน', 0.4935453),
 ('โครส_สูน', 0.48548812),
 ('ตึ๊ก_หางปลา', 0.4827577),
 ('โครส_กัลย์', 0.48175973),
 ('ทึนทึก_นิรมล', 0.4639709),
 ('คาร์นิวัล_ศิวลึงค์', 0.46182168),
 ('คาร์นิวัล_กรกช', 0.45477772),
 ('พี่_ปุ๊ก', 0.45471472),
 ('เกอิชา_จัณฑาล', 0.45177805),
 ('ทึนทึก_เสงี่ยม', 0.4505357),
 ('โครส_ฉัตต์', 0.44903755),
 ('โครส_ก๊อ', 0.4475208),
 ('คาร์นิวัล_สูน', 0.44722238),
 ('โครส_กรกช', 0.44680458),
 ('ราชินีนาถ_สร้อยสน', 0.44483465),
 ('ซิค_ทรุป', 0.4445864),
 ('พนิต_กระทาชาย', 0.44405895),
 ('หญิง_คู่หมั้น', 0.4433737),
 ('ญี่ปุ่น_จีน', 0.44289845),
 ('ยป_ศิวลึงค์', 0.44226435),
 ('พนิต_ติฐ์', 0.44191387),
 ('ตึ๊ก_กระบวย', 0.44134605),
 ('ยป_ฤก', 0.4412611),
 ('คาร์นิวัล_เดนิส', 0.4409383),
 ('โครส_เตื้อง', 0.4398851),
 ('คาร์เนกี_ปาสเตอร์', 0.43937626),
 ('บ๋าย_ก๊อ', 0.4385701),
 ('ทึนทึก_หัวแหลม', 0.4378058),
 ('เฮเลนา_สร้อยสน', 0.43597776),
 ('คาร์นิวัล_เขามอ', 0.43376788),
 ('พนิต_มู

# Exploratory analysis: Identifying the gender subspace. /Direct bias
- bias present in the embedding geometrically
- Language use is messy
- Word pairs do not always behave as expected
- คำว่าชายแปลได้หลายอย่าง (น. มนุษย์เพศผู้ซึ่งโดยกำเนิดมีลึงค์เป็นอวัยวะสืบพันธุ์, น. ส่วนริมหรือปลายของสิ่งของบางอย่าง, ก. เดินเลียบเคียงไป เช่น ชายไปดู.)
- to more robustly estimate bias, we shall aggregate across multiple paried comparisons by combining several gender directions. This direction helps us to quantify direct andindirect biases in words and associations.
- gender pair differences are not parallel in practice (different biases in differnt gender pairs, polysemy)
- to identify the gender subspace, we took the ten gender pairs and computed its principal components.

In [22]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)

10 gender pairs
- หญิง-ชาย
- ผู้หญิง-ผู้ชาย
- ภรรยา-สามี
- ราชินี-ราชา
- พระราชินี-พระราชา
- เธอ-เขา
- ธิดา-บุตร
- เมีย-ผัว
- สวย-หล่อ
- เจ้าหญิง-เจ้าชาย



In [23]:
gender_dir = np.zeros(shape=(10,100))
gender_dir[0]=norm_wv['หญิง'] - norm_wv['ชาย']
gender_dir[1]=norm_wv['ผู้หญิง'] - norm_wv['ผู้ชาย']
gender_dir[2]=norm_wv['ภรรยา'] - norm_wv['สามี']
gender_dir[3]=norm_wv['ราชินี'] - norm_wv['ราชา']
gender_dir[4]=norm_wv['พระราชินี'] - norm_wv['พระราชา']
gender_dir[5]=norm_wv['เธอ'] - norm_wv['เขา']
gender_dir[6]=norm_wv['ธิดา'] - norm_wv['บุตร']
gender_dir[7]=norm_wv['เมีย'] - norm_wv['ผัว']
gender_dir[8]=norm_wv['สวย'] - norm_wv['หล่อ']
gender_dir[9]=norm_wv['เจ้าหญิง'] - norm_wv['เจ้าชาย']
pca.fit(gender_dir)

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [226]:
pca.explained_variance_ratio_

array([0.26804551, 0.17610799, 0.14730669])

### measuring direct bias

In [28]:
sum_dir = 0.0
for job in occupation_list:
    sum_dir+=np.abs(cosine_similarity([norm_wv[job]],[g])[0][0])
    
direct_bias = sum_dir/float(len(occupation_list))

In [29]:
direct_bias

0.1024203646445326

This number confirms that many occupation words have substantial component along the gender direction

# Debias
The debiasing algorithms are defined in terms of sets of words rather than just pairs, for generality, sothat we can consider other biases such as racial or religious biases.  We also assume that we have a setof words to neutralize
1. Identify gender subspace,
2. Neutralize and Equalize or Soften

In [145]:
occupation_list=['พยาบาล','แพทย์','ไกด์','นักสืบ','หมอตำแย','ดีไซเนอร์','ศิลปิน','ตำรวจ','ทหาร','อัยการ'
                 ,'แอร์โฮสเตส','นักเคมี', 'เภสัชกร','ช่าง','ช่างภาพ','นักการเมือง','นักการทูต','ทนาย'
                 ,'กะลาสี','นักวิทยาศาสตร์','นักแสดง','บรรณาธิการ','ผู้กำกับ','พี่เลี้ยง','มัคคุเทศก์','คนงาน'
                 ,'บรรณาธิการ','บรรณารักษ์','นักเขียน','จิตแพทย์','เพชฌฆาต','สัตวแพทย์','คอลัมนิสต์','มือปืน'
                ,'นักข่าว','นักธุรกิจ','นักมวย','นักบิน','คนใช้','คนสวน','ชาวไร่','ชาวนา','นักกีฬา','นักวิ่ง'
                ,'จิตรกร','นักร้อง','สถาปนิก','ศาสตราจารย์','กรรมกร','อาจารย์','ครู','วิศวกร','ศัลยแพทย์']

###  Identify gender subspace.

In [188]:
 from sklearn.decomposition import TruncatedSVD
sum_w = 0.0
for job in occupation_list:
    sum_w+=norm_wv[job]
mean_w = sum_w/float(len(occupation_list))
C = 0.0
for job in occupation_list:
    w_minus_u = np.expand_dims((norm_wv[job]-mean_w), axis=0)
    C+= (w_minus_u.T*w_minus_u)/float(len(occupation_list))
print(C.shape)
svd = TruncatedSVD(n_components=3, n_iter=7, random_state=42)  
svd.fit(C)


(100, 100)


TruncatedSVD(algorithm='randomized', n_components=3, n_iter=7,
       random_state=42, tol=0.0)

In [189]:
svd.components_[0].shape

(100,)

In [190]:
w_b = {}
for job in occupation_list:
    w = norm_wv[job]
    w_b[job]=0.0
    for component in svd.components_:
        w_b[job] += np.dot(norm_wv[job],component)*component


###  Hard de-biasing

In [191]:
equality_sets= [['หญิง','ชาย'],['ผู้หญิง','ผู้ชาย'],['ภรรยา','สามี'],
                ['ราชินี','ราชา'],['พระราชินี','พระราชา'],
                ['เธอ','เขา'],['ธิดา','บุตร'],['เมีย','ผัว'],
                ['สวย','หล่อ'],['เจ้าหญิง','เจ้าชาย']]


for e in equality_sets:
    for word in e:
        w = norm_wv[word]
        w_b[word]=0.0
        for component in svd.components_:
            w_b[word] += np.dot(norm_wv[word],component)*component



In [192]:
#neutralize
#re_emb = {}
for job in occupation_list:
    w = norm_wv[job]
    w=(w-w_b[job])/np.linalg.norm(w-w_b[job])
    new_wv[job] = w

In [194]:
import math
#equalize
for e in equality_sets:
    mean_u = 0.0 
    for w in e:
        mean_u+=norm_wv[w]/float(len(e))
    #find u_b
    mean_b = 0.0
    for component in svd.components_:
        mean_b += np.dot(mean_u,component)*component  
    v = mean_u - mean_b
    for w in e:
        new_wv[w] = v+np.sqrt(1-np.linalg.norm(v)**2)*((w_b[w]-mean_b)/np.linalg.norm(w_b[w]-mean_b))

    

In [195]:
new_wv['ชาย']

array([ 0.11532686, -0.02693493, -0.05867063,  0.011836  ,  0.05868027,
       -0.03522775,  0.06792599, -0.3401335 , -0.04790287, -0.0711007 ,
       -0.03791795,  0.00102654,  0.03005477, -0.03712265, -0.29998067,
        0.02153794, -0.07814035,  0.05303597, -0.15443826,  0.08890126,
        0.17677402, -0.00086754,  0.02026433,  0.17687342, -0.10849766,
       -0.1056916 , -0.11992791,  0.02618286,  0.03862328, -0.03795629,
        0.08613054,  0.09594397,  0.05854234,  0.06530775,  0.04548324,
        0.04765827, -0.0607183 , -0.00986298, -0.00450327, -0.03725593,
       -0.13093078, -0.04279272,  0.1367924 ,  0.10842488,  0.15628159,
        0.01449121,  0.02883128,  0.17109933, -0.0409249 , -0.00825369,
       -0.13573802,  0.16421162,  0.03676862, -0.07074647,  0.01504417,
       -0.0543038 ,  0.04462331, -0.0921048 ,  0.00620325, -0.09867663,
       -0.00527243, -0.10417754,  0.05524072,  0.00490671,  0.01901132,
       -0.22691786,  0.07083637, -0.02364005, -0.26644045, -0.15

In [196]:
new_wv['ผู้']

array([ 0.09975082,  0.04945838, -0.05316322, -0.09669702,  0.05562497,
       -0.09609348, -0.10846148, -0.24969679, -0.19660448,  0.130019  ,
       -0.02672227,  0.02180936,  0.07165758, -0.07599963, -0.12595549,
        0.09004294,  0.01102164,  0.10804561, -0.07208294,  0.12068284,
       -0.11767711, -0.00614392, -0.12067343,  0.10628094,  0.14157973,
       -0.0954724 , -0.12528402,  0.05848654,  0.09286825, -0.00995787,
       -0.08399997,  0.10512332,  0.06126416,  0.06203365,  0.18825686,
       -0.05462785,  0.05642693, -0.01324373, -0.08354288,  0.08038211,
        0.0450413 ,  0.06402933,  0.07703406,  0.05770518,  0.2272226 ,
        0.0678764 , -0.09754229,  0.04980717, -0.03972076, -0.02436801,
       -0.03390332,  0.01432618, -0.04416713,  0.02917718, -0.13664581,
       -0.14083566,  0.00248714, -0.04315019,  0.0086965 , -0.14716178,
        0.08661809, -0.00711311,  0.08576973, -0.01215892, -0.02711575,
       -0.12120845,  0.08712977, -0.13215059, -0.21197303,  0.02

# Evaluate

In [211]:
gender_dir = new_wv['หญิง'] - new_wv['ชาย']
gender_projection = lambda x : np.dot(x, gender_dir) / np.linalg.norm(gender_dir)
#ต้องยืดมากแค่ไหนถึงจะproject ลงบน gender_dir พอดี
new_rank_job = dict.fromkeys(occupation_list)
for n in occupation_list:
    new_rank_job[n]= gender_projection(new_wv[n])
new_rank_job = sorted(new_rank_job.items(), key=lambda kv: kv[1])
new_rank_job.reverse()

In [212]:
for new_job,old_job in zip(new_rank_job,rank_job):
    print(new_job,old_job)

('บรรณาธิการ', 1.3671843e-07) ('แอร์โฮสเตส', 0.34675175)
('ศาสตราจารย์', 1.3574187e-07) ('พยาบาล', 0.1656979)
('แพทย์', 9.863258e-08) ('อาจารย์', 0.13835084)
('อาจารย์', 9.374978e-08) ('คอลัมนิสต์', 0.13245864)
('ผู้กำกับ', 8.59373e-08) ('นักข่าว', 0.11810425)
('นักเขียน', 8.203106e-08) ('ครู', 0.11230043)
('นักวิทยาศาสตร์', 7.031234e-08) ('ผู้กำกับ', 0.07558014)
('บรรณารักษ์', 5.4687373e-08) ('นักแสดง', 0.069970086)
('วิศวกร', 5.0781132e-08) ('วิศวกร', 0.06743736)
('ศัลยแพทย์', 4.687489e-08) ('ศาสตราจารย์', 0.05827758)
('ครู', 4.687489e-08) ('ดีไซเนอร์', 0.05434611)
('นักข่าว', 4.687489e-08) ('มัคคุเทศก์', 0.05304229)
('ศิลปิน', 4.687489e-08) ('นักร้อง', 0.04557085)
('อัยการ', 3.7109288e-08) ('ไกด์', 0.043560926)
('มัคคุเทศก์', 3.124993e-08) ('ช่างภาพ', 0.037830215)
('คอลัมนิสต์', 2.9296807e-08) ('นักการทูต', 0.034043066)
('นักสืบ', 2.9296807e-08) ('ศัลยแพทย์', 0.03171372)
('ตำรวจ', 2.7343686e-08) ('บรรณาธิการ', 0.030348293)
('นักกีฬา', 2.3437446e-08) ('ศิลปิน', 0.023446834)
('สัตวแพท